name: Build and Push ComfyDock Images

on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      comfyui_version:
        description: "ComfyUI version or branch (e.g. master, 1.3.0, etc.)"
        required: false
        default: "master"

  # Daily schedule
  schedule:
    - cron: '30 11 * * *'  # Runs once a day at 11:30 UTC = 3:30 AM PST

jobs:
  # New job to determine the ComfyUI version once
  determine-version:
    runs-on: ubuntu-latest
    outputs:
      comfyui_version: ${{ steps.set_version.outputs.comfyui_version }}
    steps:
      - name: Get Latest ComfyUI Release (if scheduled)
        id: get_latest
        if: ${{ github.event_name == 'schedule' }}
        run: |
          LATEST=$(curl -s https://api.github.com/repos/comfyanonymous/ComfyUI/releases \
            | jq -r '[.[] | select(.prerelease==false)] | first | .tag_name')
          echo "latest_version=$LATEST" >> $GITHUB_OUTPUT

      - name: Set ComfyUI Version
        id: set_version
        run: |
          VERSION=""
          if [ -n "${{ github.event.inputs.comfyui_version }}" ]; then
            VERSION="${{ github.event.inputs.comfyui_version }}"
            echo "Using user-specified ComfyUI version: $VERSION"
          elif [ "${{ github.event_name }}" == "schedule" ] && [ -n "${{ steps.get_latest.outputs.latest_version }}" ]; then
            VERSION="${{ steps.get_latest.outputs.latest_version }}"
            echo "Using latest ComfyUI release: $VERSION"
          else
            VERSION="master"
            echo "Using default ComfyUI version: $VERSION"
          fi
          echo "comfyui_version=$VERSION" >> $GITHUB_OUTPUT

  build-and-push:
    needs: determine-version # Wait for the version to be determined
    runs-on: ubuntu-latest

    # Only skip the scheduled build if on a non-default branch
    # Note: This condition applies to the whole job now. If the schedule runs
    # on a non-main branch, NO matrix jobs will start.
    if: github.event_name != 'schedule' || github.ref == 'refs/heads/main'

    # Define your version combos using strategy matrix
    strategy:
      fail-fast: false # Prevent other jobs from stopping if one fails
      matrix:
        python: ["3.10", "3.12"]      # Standard Python versions
        cuda: ["11.8", "12.4"]       # Standard CUDA versions
        pytorch: ["stable"]          # Standard PyTorch versions
        include:
          # Add your unique combination here
          - python: "3.12"
            cuda: "12.8"
            pytorch: "stable"
          # Add more unique combinations as needed
          # - python: "3.x"
          #   cuda: "1x.y"
          #   pytorch: "..."

    # Env vars available to all matrix jobs
    env:
      DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
      # COMFYUI_VERSION is now accessed via needs.determine-version.outputs.comfyui_version

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Check if the specific tag for THIS matrix combination exists
      - name: Check if tag already built
        id: check_tag
        # Only run the check for scheduled events
        if: ${{ github.event_name == 'schedule' }}
        run: |
          PY="${{ matrix.python }}"
          CU="${{ matrix.cuda }}"
          PT="${{ matrix.pytorch }}"
          COMFYUI_VERSION="${{ needs.determine-version.outputs.comfyui_version }}"
          TAG_NAME="${COMFYUI_VERSION}-py${PY}-cuda${CU}-pt${PT}"

          echo "Checking Docker Hub for tag: $TAG_NAME for user ${DOCKERHUB_USERNAME}"
          # Check if tag exists by trying to fetch its manifest
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
            "https://hub.docker.com/v2/repositories/${DOCKERHUB_USERNAME}/comfydock-env/tags/${TAG_NAME}")

          if [ "$STATUS_CODE" -eq 200 ]; then
            echo "Tag $TAG_NAME already exists."
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "Tag $TAG_NAME does not exist (HTTP status: $STATUS_CODE)."
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      # Login - skip if scheduled and tag already exists
      - name: Login to Docker Hub
        if: ${{ github.event_name != 'schedule' || steps.check_tag.outputs.exists != 'true' }}
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} # Use secret directly

      # Build & push - skip if scheduled and tag already exists
      - name: Build, Push, and Clean up
        if: ${{ github.event_name != 'schedule' || steps.check_tag.outputs.exists != 'true' }}
        run: |
          # Get versions from matrix context and needs context
          PY="${{ matrix.python }}"
          CU="${{ matrix.cuda }}"
          PT="${{ matrix.pytorch }}"
          COMFYUI_VERSION="${{ needs.determine-version.outputs.comfyui_version }}"

          TAG="${COMFYUI_VERSION}-py${PY}-cuda${CU}-pt${PT}"
          IMAGE_NAME="${DOCKERHUB_USERNAME}/comfydock-env:${TAG}"

          echo "Processing image: $IMAGE_NAME"
          echo "Using Python: $PY, CUDA: $CU, PyTorch: $PT, ComfyUI: $COMFYUI_VERSION"

          # Convert CUDA version format (e.g., "12.4" to "cu124")
          CU_STRIPPED="${CU//./}"
          CUDA_ARG="cu${CU_STRIPPED}"

          echo "Building image..."
          docker build \
            --build-arg COMFYUI_VERSION="${COMFYUI_VERSION}" \
            --build-arg CUDA_VERSION="${CUDA_ARG}" \
            --build-arg PYTHON_VERSION="${PY}" \
            --build-arg PYTORCH_VERSION="${PT}" \
            -t "$IMAGE_NAME" .

          echo "Pushing image: $IMAGE_NAME"
          docker push "$IMAGE_NAME"

          echo "Cleaning up image: $IMAGE_NAME"
          docker rmi -f "$IMAGE_NAME"

          # Clean up builder cache to free up space
          echo "Cleaning up builder cache..."
          docker builder prune -f

          # Optional: more aggressive cleanup (might impact performance if builds share layers)
          # echo "Running system prune..."
          # docker system prune -af

  # Optional final cleanup job after all matrix builds complete
  final-cleanup:
    runs-on: ubuntu-latest
    needs: build-and-push # Run after all matrix jobs are done (or failed if fail-fast is false)
    # Always run this cleanup step, even if matrix jobs were skipped or failed
    if: ${{ always() }}
    steps:
      - name: Docker System Prune
        run: |
          echo "Running final Docker system prune..."
          docker system prune -af
